### ISSUE TITLE
Define team workflow in CONTRIBUTING.md

### ISSUE THREAD

**Issue by uxFeranmi** [Team-Denver/workflow-test-repo#5]
Please review my work and give feedback. Check the pull request.

**Comment by cirqlar** [comment]
It looks good.
There's a typo in step 3 under `All Team Members - Pulling Remote`
fecthed instead of fetched

But otherwise, it looks good.

**Comment by Stacalpha** [comment]
Thanks.

**Comment by Stacalpha** [comment]
closes #5

**Comment by Stacalpha** [comment]
Ok. Got the pull request reference down. Perhaps I should add this pr-issue-project linking process to the document.

**Comment by JonathanJude** [comment]
@Stacalpha this is good! I cant see me being so serious and organized with my projects like this 😭😭

**Comment by Stacalpha** [comment]
Lol. Thanks.
